version: "3.3"
services:
  workflow-service:
    depends_on:
      - mysql-db
    image: nassimbenhassine/workflow-service
    container_name: workflow-service
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT

volumes:
  db: